updated the css file and js
dosanjhkiran/weather_dashboard pull request #11
Opened 2024-07-02 13:21 UTC by dosanjhkiran

please review the code

2024-07-02 14:34 UTC, ANAZ0004 commented on assets/js/dashboard.js
> -    // API fetch request | "https://www.googleapis.com/customsearch/v1?key={API key}&cx={PSE ID}&q={city name}&searchType=image&num=1"
Why trim the documentation?

2024-07-02 14:35 UTC, ANAZ0004 commented on assets/js/dashboard.js
> -    // API fetch request | "https://www.googleapis.com/customsearch/v1?key={API key}&cx={PSE ID}&q={city name}&searchType=image&num=1"
Why trim this documentation?

2024-07-02 14:53 UTC, ANAZ0004 requested changes
Great work with the CSS, the website is functional and stylish!
Please take a look at some comments and suggestions I have attached to the `dashboard.js` file. I have identified a few issues and suggested ways to address them.
Great job, Kirandeep!

2024-07-02 14:53 UTC, ANAZ0004 commented on assets/js/dashboard.js
> +    fetchWithRetry(googleAPIURL.concat("key=", googleAPIKeyAN, "&cx=", googlePSEID, "&q=", searchQuery, "&num=1"))
fetchWithRetry is not an existing function, **we would need to make our own.** (May be outside the course content).
I think it is better to keep the old way but **it's okay to remove declaration of fetchURLGoogleDesc variable** and instead place the concatenation inside the function parameter.
**This currently does not work.**
"Uncaught ReferenceError: fetchWithRetry is not defined."

2024-07-02 14:53 UTC, ANAZ0004 commented on assets/js/dashboard.js
> +    fetchWithRetry(googleAPIURL.concat("key=", googleAPIKeyAN, "&cx=", googlePSEID, "&q=", searchQuery, "&searchType=image&num=1"))
Same as above.
fetchWithRetry is not an existing function, **we would need to make our own.** (May be outside the course content).
I think it is better to keep the old way but **it's okay to remove declaration of fetchURLGoogleImage variable** and instead place the concatenation inside the function parameter.
**This currently does not work.**
"Uncaught ReferenceError: fetchWithRetry is not defined."

2024-07-02 14:53 UTC, ANAZ0004 commented on assets/css/style.css
CSS is great and functional!

2024-07-02 14:53 UTC, ANAZ0004 commented on assets/js/dashboard.js
> +    let forecastContainer = document.getElementById("forecast-container");
There is currently no element with ID "forecast-container", thus, this function does not work.

2024-07-02 14:53 UTC, ANAZ0004 commented on assets/js/dashboard.js
> +function displayWindSpeed(speed, elementId) {
Great work with this function, however, it is not being called anywhere at the moment, thus, is not being executed. Feel free to implement code to address this.

2024-07-02 15:02 UTC, ANAZ0004 requested changes
Just a couple CSS changes regarding footer behaviour.

2024-07-02 15:02 UTC, ANAZ0004 commented on assets/css/style.css
> +    position: absolute;
```suggestion
    position: fixed;
```
For correct footer behaviour :)

2024-07-02 15:02 UTC, ANAZ0004 commented on assets/css/style.css
> +    bottom: 0;
```suggestion
    left: 0;
    bottom: 0;
```
To get rid of small gap present in certain viewports.

2024-07-03 09:33 UTC, jairatagle approved these changes

2024-07-03 09:33 UTC, ANAZ0004 approved these changes

2024-07-03 09:34 UTC, jairatagle approved these changes

2024-07-03 09:46 UTC, jairatagle approved these changes

2024-07-03 09:46 UTC, merged

2024-07-03 09:50 UTC, dosanjhkiran reviewed
goodjob